###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    ${{PROJECT_NAME}}-web:
        image: nginx:alpine
        container_name: ${{PROJECT_NAME}}-web
        working_dir: /application
        volumes:
            - ${VOLUME_PATH}:/application
            - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
        ports:
            - ${PORT_HTTP}:80

    ${{PROJECT_NAME}}-php:
        build: phpdocker/php-fpm
        container_name: ${{PROJECT_NAME}}-php
        working_dir: /application
        volumes:
            - ${VOLUME_PATH}:/application
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        ports:
            - ${PORT_PHP}:9000
